version: '3.7'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  main:
    image: starfield
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on: 
      - db
    ports:
      - "8080:8080"

volumes:
  mongodb_data_container: