// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Module struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewShip struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Ship struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	Modules []*Module `json:"modules"`
}
