// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewShip struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Ship struct {
	ID          string `json:"id" bson: "_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}
